### ISSUE TITLE
Object.prototype.toString returns incorrect result when called on null or undefined

### ISSUE THREAD

**Issue by kevinpschaaf** [es-shims/get-own-property-symbols#16]
**Repro**:
Live: https://jsbin.com/risezaf/edit?html,console
```js
console.log(Object.prototype.toString.call(undefined));
console.log(Object.prototype.toString.call(null));
console.log(Object.prototype.toString.call(window));
```
**Expected:**
```
[object Undefined]
[object Null]
[object Window]
```
**Actual:**
```
[object Window]
[object Window]
[object Window]
```

In loose mode, [this code](https://github.com/es-shims/get-own-property-symbols/blob/4e397dc596a3df1ad42faa1697cffff7fe2a7016/src/get-own-property-symbols.js#L258-L264) evaluates the undefined/null `this` as `window`, which gives different semantics from the native implementation of `toString` when called against null/undefined.  Seems like that function should also be set to `'use strict'` mode, so it can differentiate `null`/`undefined` from explicitly being called on `window` (and then guard the `this[Symbol.toStringTag]` call appropriately).

**Comment by ljharb** [comment]
Closed in #18.
